version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "23:35"
      # Use Japan Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
    target-branch: "develop"
